---
title: "Farmland Biodiversity and the Footprint of Agriculture"
type: "article"
year: "2007"
publication: "Science"
doi: "https://doi.org/10.1126/science.1136607"
toc: false
categories:
  - biodiversity
  - agri-environment schemes
  - conservation biology
  - journal article
---

## Citation

> Butler, S. J., Vickery, J. A. and Norris, K. Farmland Biodiversity and the Footprint of Agriculture. *Science* **315**, 5810 (2007). https://doi.org/10.1126/science.1136607

## Abstract

Sustainable development requires the reconciliation of demands for biodiversity conservation and increased agricultural production. Assessing the impact of novel farming practices on biodiversity and ecosystem services is fundamental to this process. Using farmland birds as a model system, we present a generic risk assessment framework that accurately predicts each species' current conservation status and population growth rate associated with past changes in agriculture. We demonstrate its value by assessing the potential impact on biodiversity of two controversial land uses, genetically modified herbicide-tolerant crops and agri-environment schemes. This framework can be used to guide policy and land management decisions and to assess progress toward sustainability targets.