---
title: "The costs of delivering environmental outcomes with land sharing and land sparing"
type: "article"
year: "2022"
publication: "People and Nature"
doi: "https://doi.org/10.1002/pan3.10422"
toc: false
categories: 
    - agri-environment schemes
    - biodiversity conservation
    - carbon emissions
    - choice experiment
    - environmental economics
    - land sharing
    - land sparing
    - land use policy
---

## Citation

> Collas, L., Crastes dit Sourd, R., Finch, T., Green, R., Hanley, N., & Balmford, A. The costs of delivering environmental outcomes with land sharing and land sparing. *People Nat.*, **00**, 1– 13 (2022). doi: 10.1002/pan3.10422

## Abstract


1. The biodiversity and climate crises demand ambitious policies lowering the environmental impacts of farming. Most current interventions incentivise so-called land-sharing approaches to address the widespread trade-off between farm yields and on-farm environmental outcomes by compensating farmers who adopt yield-reducing interventions that encourage wildlife or reduce net emissions within farmed land.
2. Here, we present the first quantification of the likely costs to taxpayers of land sharing compared with land sparing, in which large areas are removed from production altogether because of high-yielding practices elsewhere in the landscape. Focusing on arable production in the United Kingdom, we used a choice experiment to explore farmer preferences and estimated the overall costs of contrasting agri-environment schemes that delivered increased populations of three well-studied farmland birds and reduced net carbon emissions in England. We included capital, administration and monitoring costs, and lost food production.
3. Sparing delivered our target biodiversity and carbon emission outcomes at 79% of the food production cost and 48% of the taxpayer cost of sharing. The difference in subsidy payments required by farmers roughly tracked lost food production but other costs favoured sparing even more strongly.
4. The cost-related merits of sparing would probably increase further in studies incorporating (1) the many species and ecosystem services not deliverable on farmland, (2) the costs of food imports to compensate domestic lost production and (3) countries without as long and extensive a history of agriculture as the United Kingdom.
5. Our results suggest that, for at least some conservation outcomes, continuing a land-sharing approach in countries such as the United Kingdom is not only an inefficient use of government funds but also undermines conservation and food security in food-exporting countries which bear the burden of compensating domestic production forgone in the name of conservation.
