---
title: "Blue space exposure, health and well-being: Does freshwater type matter?"
type: "article"
year: "2022"
publication: "Landscape and Urban Planning"
doi: "https://doi.org/10.1016/j.landurbplan.2022.104446"
toc: false
categories:
  - mental health
  - canal
  - green space
  - nature contact
  - WHO-5
---

## Citation

> McDougall, C. W., Hanley, C., Quilliam, R. S. & Oliver, D. M. Blue space exposure, health and well-being: Does freshwater type matter? *Landsc. Urban Plan.*, **224**, 104446 (2022). doi: 10.1016/j.landurbplan.2022.104446

## Abstract

There is growing evidence that spending time in or around water bodies or ‘blue spaces’ can result in improved human health. To date, investigations of the health-promoting potential of blue space exposure have mostly focused on coastal environments. Despite their vital role in many urban landscapes, freshwater blue spaces have received less research attention and very little is known about the potential of different freshwater blue space types to impact health and well-being. This study used logistic and negative binomial regression modelling to quantify the association between proximity and exposure to different freshwater blue space types and general health and mental well-being in Scotland. A nationwide online panel survey (n = 1392) was used to determine how far respondents lived from lakes, rivers and canals and to establish how often they visited these blue spaces. Living within a ten minute walking distance of lakes, rivers or canals was not associated with greater general health or mental well-being. However, frequently visiting rivers and canals but not lakes, in the last month, was associated with greater mental well-being. Frequent green space visitation, but not blue space visitation, was associated with higher odds of reporting good general health. Taken together, our findings suggest that freshwater blue space exposure can provide mental well-being benefits. However, the provision of these benefits may vary among different freshwater blue space types. Understanding the health and well-being impact of different freshwater environments, therefore, offers opportunities for evidence-based policymaking to maximise the health-promoting potential of urban blue spaces.