---
title: "Neighbourhood blue space and mental health: A nationwide ecological study of antidepressant medication prescribed to older adults"
type: "article"
year: "2021"
publication: "Landscape and Urban Planning"
doi: "https://doi.org/10.1016/j.landurbplan.2021.104132"
toc: false
categories:
  - freshwater
  - coastal
  - green space
  - urban planning
  - depression
  - healthy ageing
---

## Citation

> McDougall, C.W., Hanley, N., Quilliam, R. S., Bartie, P.J., Robertson, T., Griffiths, M. & Oliver, D.M. Neighbourhood blue space and mental health: A nationwide ecological study of antidepressant medication prescribed to older adults. *Landsc. Urban Plan.*, **214**, 104132 (2021). doi: 10.1016/j.landurbplan.2021.104132

## Abstract

As global populations age rapidly, older adult mental health is becoming an increasingly important public health issue. The consequences of poor mental health in later life are severe and include reduced physical and cognitive functioning and greater risk of morbidity and mortality. Neighbourhood characteristics, such as the presence of aquatic environments - or ‘blue spaces’ - can positively impact mental health. However, evidence supporting the potential of neighbourhood blue space to promote mental health among older adults remains tentative. This study used negative binomial regression modelling to quantify the association between multiple metrics of neighbourhood blue space availability and antidepressant medication prevalence among older adults in Scotland. The study combined nationwide antidepressant prescription data for over two million older adults and geospatial data of blue space availability for over six thousand neighbourhoods and adjusted for a range of demographic and socioeconomic covariates. The availability of both freshwater and coastal blue space was associated with lower antidepressant medication prevalence among older adults in Scotland. Specifically, high neighbourhood freshwater coverage (>3%) (p < 0.001) and residing in close proximity (<1 km) to the coast (p < 0.001) and large freshwater lakes (p < 0.05) was associated with lower antidepressant medication prevalence. Our findings also suggest that neighbourhood blue space availability may have a greater impact on antidepressant medication prevalence among older adults than neighbourhood green space availability. Freshwater and coastal blue space, therefore, merit greater consideration in public health and urban planning policy and in the design of environments that aim to promote mental health and healthy aging.