---
title: "Ecological and economic implications of alternative metrics in biodiversity offset markets"
type: "article"
year: "2022"
publication: "Conservation Biology"
doi: "https://doi.org/10.1111/cobi.13906"
toc: false
categories:
  - biodiversity offsets
  - biodiversity metrics
  - biodiversity loss
  - simulation model
  - no net loss
---

## Citation

> Simpson K., de Vries F., Dallimer M, Armsworth P & Hanley N. Ecological and Economic Implications of Alternative Metrics in Biodiversity Offset Markets. *Conserv. Biol.*, **36**, e13906 (2022). doi: 10.1111/cobi.13906

## Abstract

Policy tools are needed that allow reconciliation of human development pressures with conservation priorities. Biodiversity offsetting can be used to compensate for ecological losses caused by development activities. Landowners can choose to undertake conservation actions, including habitat restoration, to generate biodiversity offsets. Consideration of the incentives facing landowners as potential biodiversity offset providers and developers as potential buyers of credits is critical when considering the ecological and economic landscape-scale outcomes of alternative offset metrics. There is an expectation that landowners will always seek to conserve the least profitable land parcels, and, in turn, this determines the spatial location of biodiversity offset credits. We developed an ecological-economic model to compare the ecological and economic outcomes of offsetting for a habitat-based metric and a species-based metric. We were interested in whether these metrics would adequately capture the indirect benefits of offsetting on species not considered under a no-net-loss policy. We simulated a biodiversity offset market for a case study landscape, linking species distribution modeling and an economic model of landowner choice based on economic returns of the alternative land management options (restore, develop, or maintain existing land use). Neither the habitat nor species metric adequately captured the indirect benefits of offsetting on related habitats or species. The underlying species distributions, layered with the agricultural and development rental values of parcels, resulted in very different landscape outcomes depending on the metric chosen. If policy makers are aiming for the metric to act as an indicator to mitigate impacts on a range of closely related habitats and species, then a simple no-net-loss target is not adequate. Furthermore, to achieve the most ecologically beneficial design of offsets policy, an understanding of the economic decision-making processes of the landowners is needed.